name: Run Basic Commands

on:
  pull_request:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: npm install -g markdownlint-cli
    - run: markdownlint src
