name: Pull Request Pipeline

on:
  pull_request:
  # push:
  #   branches:
  #   - main # Push events on master branch

jobs:
# https://github.com/chef/github-workflows/blob/main/.github/workflows/yaml-lint.yml
  yaml-lint:
    uses: ./.github/workflows/yaml-lint.yml
  pr-check:
    if: always()
    needs:
      - yaml-lint
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          # allowed-failures: markdown-link-checker
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
